
module Test_LVM =

let conf = "# Generated by LVM2: date

contents = \"Text Format Volume Group\"
version = 1

description = \"Created *after* executing 'eek'\"

creation_host = \"eek\"		# Linux eek
creation_time = 6666666666	# eeeek

VG1 {
	id = \"uuid-uuid-uuid-uuid\"
	seqno = 2
	status = [\"RESIZEABLE\", \"READ\", \"WRITE\"]
	extent_size = 8192		# 4 Megabytes
	max_lv = 0
	max_pv = 0

	physical_volumes {
		pv0 {
			id = \"uuid-uuid-uuid-uuid\"
			device = \"/dev/sda6\"	# Hint only

			status = [\"ALLOCATABLE\"]
			pe_start = 123
			pe_count = 123456	# many Gigabytes
		}
	}

	logical_volumes {
		LogicalEek {
			id = \"uuid-uuid-uuid-uuid\"
			status = [\"READ\", \"WRITE\", \"VISIBLE\"]
			segment_count = 1

			segment1 {
				start_extent = 0
				extent_count = 123456	# beaucoup Gigabytes

				type = \"striped\"
				stripe_count = 1	# linear

				stripes = [
					\"pv0\", 0
				]
			}
		}
	}
}
"

test LVM.int get "5" = { "int" = "5" }
test LVM.str get "\"abc\"" = { "str" = "abc"}
test LVM.assignment get "a=5\n" = { "assign" { "a" { "int" = "5" } } }
test LVM.lns get "\n" = {}
test LVM.lns get "#foo\n" = { "#comment" = "foo"}

test LVM.lns get "# Generated by LVM2: date

contents = \"Text Format Volume Group\"
version = 1

description = \"Created *after* executing 'eek'\"

creation_host = \"eek\"		# Linux eek
creation_time = 6666666666	# eeeek\n" =
	{ "#comment" = "Generated by LVM2: date" }
	{}
	{ "assign"
		{ "contents"
			{ "str" = "Text Format Volume Group" }
		}
	}
	{ "assign"
		{ "version"
			{ "int" = "1" }
		}
	}
	{}
	{ "assign"
		{ "description"
			{ "str" = "Created *after* executing 'eek'" }
		}
	}
	{}
	{ "assign"
		{ "creation_host"
			{ "str" = "eek" }
			{ "#comment" = "Linux eek" }
		}
	}
	{ "assign"
		{ "creation_time"
			{ "int" = "6666666666" }
			{ "#comment" = "eeeek" }
		}
	}


test LVM.assignment get "a = []\n" =
{ "assign" { "a" { "list" } } }

test LVM.assignment get "a = [\"foo\"]\n" =
{ "assign" { "a" { "list" { "1" { "str" = "foo" } } } } }

test LVM.assignment get "a = [\"foo\",\"zap\"]\n" =
{ "assign" { "a" { "list" { "1" { "str" = "foo" } } { "2" { "str" = "zap" } } } } }

test LVM.lns get conf =
	{ "#comment" = "Generated by LVM2: date" }
	{}
	{ "assign"
		{ "contents"
			{ "str" = "Text Format Volume Group" }
		}
	}
	{ "assign"
		{ "version"
			{ "int" = "1" }
		}
	}
	{}
	{ "assign"
		{ "description"
			{ "str" = "Created *after* executing 'eek'" }
		}
	}
	{}
	{ "assign"
		{ "creation_host"
			{ "str" = "eek" }
			{ "#comment" = "Linux eek" }
		}
	}
	{ "assign"
		{ "creation_time"
			{ "int" = "6666666666" }
			{ "#comment" = "eeeek" }
		}
	}
	{}
	{ "block"
		{ "VG1"
			{ "assign"
				{ "id"
					{ "str" = "uuid-uuid-uuid-uuid" }
				}
			}
			{ "assign"
				{ "seqno"
					{ "int" = "2" }
				}
			}
			{ "assign"
				{ "status"
					{ "list"
						{ "1"
							{ "str" = "RESIZEABLE" }
						}
						{ "2"
							{ "str" = "READ" }
						}
						{ "3"
							{ "str" = "WRITE" }
						}
					}
				}
			}
			{ "assign"
				{ "extent_size"
					{ "int" = "8192" }
					{ "#comment" = "4 Megabytes" }
				}
			}
			{ "assign"
				{ "max_lv"
					{ "int" = "0" }
				}
			}
			{ "assign"
				{ "max_pv"
					{ "int" = "0" }
				}
			}
			{}
			{ "block"
				{ "physical_volumes"
					{ "block"
						{ "pv0"
							{ "assign"
								{ "id"
									{ "str" = "uuid-uuid-uuid-uuid" }
								}
							}
							{ "assign"
								{ "device"
									{ "str" = "/dev/sda6" }
									{ "#comment" = "Hint only" }
								}
							}
							{}
							{ "assign"
								{ "status"
									{ "list"
										{ "1"
											{ "str" = "ALLOCATABLE" }
										}
									}
								}
							}
							{ "assign"
								{ "pe_start"
									{ "int" = "123" }
								}
							}
							{ "assign"
								{ "pe_count"
									{ "int" = "123456" }
									{ "#comment" = "many Gigabytes" }
								}
							}
						}
					}
				}
			}
			{}
			{ "block"
				{ "logical_volumes"
					{ "block"
						{ "LogicalEek"
							{ "assign"
								{ "id"
									{ "str" = "uuid-uuid-uuid-uuid" }
								}
							}
							{ "assign"
								{ "status"
									{ "list"
										{ "1"
											{ "str" = "READ" }
										}
										{ "2"
											{ "str" = "WRITE" }
										}
										{ "3"
											{ "str" = "VISIBLE" }
										}
									}
								}
							}
							{ "assign"
								{ "segment_count"
									{ "int" = "1" }
								}
							}
							{}
							{ "block"
								{ "segment1"
									{ "assign"
										{ "start_extent"
											{ "int" = "0" }
										}
									}
									{ "assign"
										{ "extent_count"
											{ "int" = "123456" }
											{ "#comment" = "beaucoup Gigabytes" }
										}
									}
									{}
									{ "assign"
										{ "type"
											{ "str" = "striped" }
										}
									}
									{ "assign"
										{ "stripe_count"
											{ "int" = "1" }
											{ "#comment" = "linear" }
										}
									}
									{}
									{ "assign"
										{ "stripes"
											{ "list"
												{ "1"
													{ "str" = "pv0" }
												}
												{ "2"
													{ "int" = "0" }
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}


